In [1]:
from numpy import *
U,Sigma,VT = linalg.svd([[1,1],[7,7]])

In [2]:
U

array([[-0.14142136, -0.98994949],
       [-0.98994949,  0.14142136]])

In [3]:
Sigma

array([1.00000000e+01, 2.82797782e-16])

In [4]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [5]:
def loadExData():
    return[[1,1,1,0,0],
          [2,2,2,0,0],
          [1,1,1,0,0],
          [5,5,5,0,0],
          [1,1,0,2,2],
          [0,0,0,3,3],
          [0,0,0,1,1]]

In [6]:
Data = loadExData()
U,Sigma,VT = linalg.svd(Data)

In [7]:
U

array([[-1.77939726e-01, -1.64228493e-02, -1.80501685e-02,
         5.78781589e-01,  7.63543471e-01,  1.88532246e-01,
         1.19208924e-01],
       [-3.55879451e-01, -3.28456986e-02, -3.61003369e-02,
        -7.74715499e-01,  4.30193167e-01,  2.92770317e-01,
         1.73735935e-03],
       [-1.77939726e-01, -1.64228493e-02, -1.80501685e-02,
        -9.98107173e-02,  2.90929148e-01, -9.10725887e-01,
        -2.09089326e-01],
       [-8.89698628e-01, -8.21142464e-02, -9.02508423e-02,
         2.14092025e-01, -3.82971791e-01,  2.73306011e-02,
         1.72811368e-02],
       [-1.33954753e-01,  5.33527340e-01,  8.35107599e-01,
        -4.70561099e-16,  3.48412692e-16,  9.45105663e-17,
        -2.67155562e-17],
       [-2.15749771e-02,  7.97677135e-01, -5.13074760e-01,
         3.00502810e-02,  7.92492923e-03,  6.96939961e-02,
        -3.06882588e-01],
       [-7.19165903e-03,  2.65892378e-01, -1.71024920e-01,
        -9.01508431e-02, -2.37747877e-02, -2.09081988e-01,
         9.2064776

In [8]:
Sigma

array([9.72140007e+00, 5.29397912e+00, 6.84226362e-01, 4.11502614e-16,
       1.36030206e-16])

In [9]:
VT

array([[-5.81200877e-01, -5.81200877e-01, -5.67421508e-01,
        -3.49564973e-02, -3.49564973e-02],
       [ 4.61260083e-03,  4.61260083e-03, -9.61674228e-02,
         7.03814349e-01,  7.03814349e-01],
       [ 4.02721076e-01,  4.02721076e-01, -8.17792552e-01,
        -5.85098794e-02, -5.85098794e-02],
       [-6.14116145e-02,  6.14116145e-02,  3.22982727e-16,
        -7.04434961e-01,  7.04434961e-01],
       [ 7.04434961e-01, -7.04434961e-01, -7.05133213e-17,
        -6.14116145e-02,  6.14116145e-02]])

In [10]:
Sig3 = mat([[Sigma[0],0,0],[0,Sigma[1],0],[0,0,Sigma[2]]])

In [11]:
Sig3

matrix([[9.72140007, 0.        , 0.        ],
        [0.        , 5.29397912, 0.        ],
        [0.        , 0.        , 0.68422636]])

In [12]:
U[:,:3] * Sig3 * VT[:3,:]

matrix([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          7.75989921e-16,  7.71587483e-16],
        [ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
          3.00514919e-16,  2.77832253e-16],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          2.18975112e-16,  2.07633779e-16],
        [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
          3.00675663e-17, -1.28697294e-17],
        [ 1.00000000e+00,  1.00000000e+00, -5.48397422e-16,
          2.00000000e+00,  2.00000000e+00],
        [ 3.21319929e-16,  4.43562065e-16, -3.48967188e-16,
          3.00000000e+00,  3.00000000e+00],
        [ 9.71445147e-17,  1.45716772e-16, -1.52655666e-16,
          1.00000000e+00,  1.00000000e+00]])

In [13]:
from numpy import linalg as la

def ecludSim(inA, inB):
    return 1.0/(1.0 + la.norm(inA - inB))

def pearsSim(inA, inB):
    if len(inA) < 3: return 1.0
    return 0.5 + 0.5 * corrcoef(inA, inB, rowvar = 0)[0][1]

def cosSim(inA, inB):
    num = float(inA.T * inB)
    denom = la.norm(inA) * la.norm(inB)
    return 0.5 + 0.5 *(num/denom)

In [14]:
myMat = mat(loadExData())
myMat

matrix([[1, 1, 1, 0, 0],
        [2, 2, 2, 0, 0],
        [1, 1, 1, 0, 0],
        [5, 5, 5, 0, 0],
        [1, 1, 0, 2, 2],
        [0, 0, 0, 3, 3],
        [0, 0, 0, 1, 1]])

In [15]:
ecludSim(myMat[:,0],myMat[:,4])

0.13367660240019172

In [16]:
ecludSim(myMat[:,0],myMat[:,0])

1.0

In [17]:
cosSim(myMat[:,0],myMat[:,4])

0.5472455591261534

In [18]:
cosSim(myMat[:,0],myMat[:,0])

0.9999999999999999

In [19]:
pearsSim(myMat[:,0],myMat[:,4])

0.23768619407595815

In [20]:
pearsSim(myMat[:,0],myMat[:,0])

1.0

In [21]:
#给定相似度计算方法的条件下，用户对物品的估计评分值
def standEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0
    ratSimTotal = 0.0
    for j in range(n):
        userRating = dataMat[user,j]
        if userRating == 0:
            continue
        overLap = nonzero(logical_and(dataMat[:,item].A>0,dataMat[:,j].A>0))[0]
        if len(overLap) == 0:
            similarity = 0
        else:
            similarity = simMeas(dataMat[overLap,item],dataMat[overLap,j])
        print('the %d and %d similarity is : %f' % (item, j, similarity))
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else:
        return ratSimTotal / simTotal

In [22]:
#推荐引擎
def recommend(dataMat, user, N = 3, simMeas = cosSim, estMethod = standEst):
    unratedItems = nonzero(dataMat[user,:].A == 0)[1]
    if len(unratedItems) == 0:
        return 'you rated everything'
    itemsScores = []
    for item in unratedItems:
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        itemsScores.append((item, estimatedScore))
    return sorted(itemsScores, key = lambda jj:jj[1], reverse = True)[:N]

In [23]:
myMat = mat(loadExData())
myMat

matrix([[1, 1, 1, 0, 0],
        [2, 2, 2, 0, 0],
        [1, 1, 1, 0, 0],
        [5, 5, 5, 0, 0],
        [1, 1, 0, 2, 2],
        [0, 0, 0, 3, 3],
        [0, 0, 0, 1, 1]])

In [24]:
myMat[0,1] = myMat[0,0] = myMat[1,0] = myMat[2,0] = 4
myMat[3,3] = 2
myMat

matrix([[4, 4, 1, 0, 0],
        [4, 2, 2, 0, 0],
        [4, 1, 1, 0, 0],
        [5, 5, 5, 2, 0],
        [1, 1, 0, 2, 2],
        [0, 0, 0, 3, 3],
        [0, 0, 0, 1, 1]])

In [25]:
recommend(myMat,2)

the 3 and 0 similarity is : 0.916025
the 3 and 1 similarity is : 0.916025
the 3 and 2 similarity is : 1.000000
the 4 and 0 similarity is : 1.000000
the 4 and 1 similarity is : 1.000000
the 4 and 2 similarity is : 0.000000


[(4, 2.5), (3, 1.9703483892927431)]

In [26]:
recommend(myMat,2,simMeas = ecludSim)

the 3 and 0 similarity is : 0.240253
the 3 and 1 similarity is : 0.240253
the 3 and 2 similarity is : 0.250000
the 4 and 0 similarity is : 0.500000
the 4 and 1 similarity is : 0.500000
the 4 and 2 similarity is : 0.000000


[(4, 2.5), (3, 1.98665729687295)]

In [27]:
recommend(myMat,2,simMeas = pearsSim)

the 3 and 0 similarity is : 1.000000
the 3 and 1 similarity is : 1.000000
the 3 and 2 similarity is : 1.000000
the 4 and 0 similarity is : 1.000000
the 4 and 1 similarity is : 1.000000
the 4 and 2 similarity is : 0.000000


[(4, 2.5), (3, 2.0)]

In [28]:
def loadExData2():
    return[[2,0,0,4,4,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0,0,5],
          [0,0,0,0,0,0,0,1,0,4,0],
          [3,3,4,0,3,0,0,2,2,0,0],
          [5,5,5,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,5,0,0,5,0],
          [4,0,4,0,0,0,0,0,0,0,5],
          [0,0,0,0,0,4,0,0,0,0,4],
          [0,0,0,0,0,0,5,0,0,5,0],
          [0,0,0,3,0,0,0,0,4,5,0],
          [1,1,2,1,1,2,1,0,4,5,0]]

In [29]:
from numpy import linalg as la
U,Sigma,VT = la.svd(mat(loadExData2()))
Sigma

array([1.34342819e+01, 1.18190832e+01, 8.20176076e+00, 6.86912480e+00,
       5.29063022e+00, 3.91213561e+00, 2.94562509e+00, 2.35486137e+00,
       2.08702082e+00, 7.08715931e-01, 1.90990329e-16])

In [30]:
Sig2 = Sigma ** 2
Sig2

array([1.80479931e+02, 1.39690727e+02, 6.72688795e+01, 4.71848755e+01,
       2.79907681e+01, 1.53048050e+01, 8.67670715e+00, 5.54537209e+00,
       4.35565591e+00, 5.02278271e-01, 3.64773057e-32])

In [31]:
sum(Sig2)

497.0

In [32]:
sum(Sig2)*0.9

447.3

In [33]:
sum(Sig2[:2])

320.17065834028847

In [34]:
sum(Sig2[:3])

387.4395378556578

In [35]:
def svdEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0
    ratSimTotal = 0.0
    U,Sigma,VT = la.svd(dataMat)
    Sig4 = mat(eye(4) * Sigma[:4])
    xformedItems = dataMat.T * U[:,:4] * Sig4.I
    for j in range(n):
        userRating = dataMat[user,j]
        if userRating == 0 or j == item: continue
        similarity = simMeas(xformedItems[item, :].T, xformedItems[j,:].T)
        print('the %d and %d similarity is : %f' % (item, j, similarity))
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else:
        return ratSimTotal / simTotal

In [36]:
recommend(myMat,1,estMethod = svdEst)

the 3 and 0 similarity is : 0.441210
the 3 and 1 similarity is : 0.523799
the 3 and 2 similarity is : 0.650061
the 4 and 0 similarity is : 0.561288
the 4 and 1 similarity is : 0.475190
the 4 and 2 similarity is : 0.343564


[(4, 2.813435807030927), (3, 2.5463659978758417)]

In [37]:
recommend(myMat,1,estMethod = svdEst,simMeas = pearsSim)

the 3 and 0 similarity is : 0.074611
the 3 and 1 similarity is : 0.602337
the 3 and 2 similarity is : 0.641514
the 4 and 0 similarity is : 0.136441
the 4 and 1 similarity is : 0.576816
the 4 and 2 similarity is : 0.241017


[(4, 2.285957188386649), (3, 2.1131786800996397)]

In [38]:
def printMat(inMat, thresh = 0.8):
    for i in range(32):
        for k in range(32):
            if float(inMat[i,k]) > thresh:
                print(1)
            else:
                print(0)
        print ('')
        
def imgCompress(numSV = 3, thresh = 0.8):
    myl = []
    for line in open('E:\\python\\machinelearning\\MLDownloads\\machinelearninginaction\\Ch14\\0_5.txt').readlines():
        newRow = []
        for i in range(32):
            newRow.append(int(line[i]))
        myl.append(newRow)
    myMat = mat(myl)
    print("****original matrix*********")
    printMat(myMat,thresh)
    U,Sigma,VT = la.svd(myMat)
    SigRecon = mat(zeros((numSV,numSV)))
    for k in range(numSV):
        SigRecon[k,k] = Sigma[k]
    reconMat = U[:,:numSV] * SigRecon * VT[:numSV,:]
    print("*******************recontructed matrix using %d singular values ****************" % numSV)
    printMat(reconMat,thresh)

In [39]:
imgCompress(2)

****original matrix*********
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
0
0
0
0
1
1
1
1
1
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
1
1
1
1
1
1
1
0
0
0
0
0
1
1
1
1
1
0
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
1
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0

0
0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0